name: Daily Proverb Update

on:
  schedule:
    - cron: '5 0 * * *' # Daily at 00:05 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Update README
        run: |
          python tools/update_readme.py

      - name: Commit changes
        run: |
          if ! git diff --quiet; then
            git config user.name "github-actions"
            git config user.email "github-actions@users.noreply.github.com"
            git add README.md
            git commit -m "chore: update proverb of the day [skip ci]"
            git push
          else
            echo "No changes to commit."
